// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analysis_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalysisJob = `-- name: CreateAnalysisJob :exec
INSERT INTO analysis_jobs (
    id, user_id,
    idempotency_key,
    car_make, car_model, car_generation, car_year,
    image_keys,
    correlation_id,
    status,
    requested_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAnalysisJobParams struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	IdempotencyKey *string
	CarMake        *string
	CarModel       *string
	CarGeneration  *string
	CarYear        *int32
	ImageKeys      []byte
	CorrelationID  pgtype.UUID
	Status         string
	RequestedAt    pgtype.Timestamptz
}

func (q *Queries) CreateAnalysisJob(ctx context.Context, arg CreateAnalysisJobParams) error {
	_, err := q.db.Exec(ctx, createAnalysisJob,
		arg.ID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.CarMake,
		arg.CarModel,
		arg.CarGeneration,
		arg.CarYear,
		arg.ImageKeys,
		arg.CorrelationID,
		arg.Status,
		arg.RequestedAt,
	)
	return err
}

const getAnalysisJobByCorrelationID = `-- name: GetAnalysisJobByCorrelationID :one
SELECT id, user_id,
       idempotency_key,
       car_make, car_model, car_generation, car_year,
       image_keys,
       correlation_id,
       status, error_message,
       result, used_model_version,
       requested_at, started_at, completed_at
FROM analysis_jobs
WHERE correlation_id = $1
`

func (q *Queries) GetAnalysisJobByCorrelationID(ctx context.Context, correlationID pgtype.UUID) (AnalysisJob, error) {
	row := q.db.QueryRow(ctx, getAnalysisJobByCorrelationID, correlationID)
	var i AnalysisJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.CarMake,
		&i.CarModel,
		&i.CarGeneration,
		&i.CarYear,
		&i.ImageKeys,
		&i.CorrelationID,
		&i.Status,
		&i.ErrorMessage,
		&i.Result,
		&i.UsedModelVersion,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAnalysisJobByID = `-- name: GetAnalysisJobByID :one
SELECT id, user_id,
       idempotency_key,
       car_make, car_model, car_generation, car_year,
       image_keys,
       correlation_id,
       status, error_message,
       result, used_model_version,
       requested_at, started_at, completed_at
FROM analysis_jobs
WHERE id = $1
`

func (q *Queries) GetAnalysisJobByID(ctx context.Context, id pgtype.UUID) (AnalysisJob, error) {
	row := q.db.QueryRow(ctx, getAnalysisJobByID, id)
	var i AnalysisJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.CarMake,
		&i.CarModel,
		&i.CarGeneration,
		&i.CarYear,
		&i.ImageKeys,
		&i.CorrelationID,
		&i.Status,
		&i.ErrorMessage,
		&i.Result,
		&i.UsedModelVersion,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAnalysisJobByUserAndIdempotencyKey = `-- name: GetAnalysisJobByUserAndIdempotencyKey :one
SELECT id, user_id,
       idempotency_key,
       car_make, car_model, car_generation, car_year,
       image_keys,
       correlation_id,
       status, error_message,
       result, used_model_version,
       requested_at, started_at, completed_at
FROM analysis_jobs
WHERE user_id = $1
  AND idempotency_key = $2
`

type GetAnalysisJobByUserAndIdempotencyKeyParams struct {
	UserID         pgtype.UUID
	IdempotencyKey *string
}

func (q *Queries) GetAnalysisJobByUserAndIdempotencyKey(ctx context.Context, arg GetAnalysisJobByUserAndIdempotencyKeyParams) (AnalysisJob, error) {
	row := q.db.QueryRow(ctx, getAnalysisJobByUserAndIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i AnalysisJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.CarMake,
		&i.CarModel,
		&i.CarGeneration,
		&i.CarYear,
		&i.ImageKeys,
		&i.CorrelationID,
		&i.Status,
		&i.ErrorMessage,
		&i.Result,
		&i.UsedModelVersion,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAnalysisJobsByUserID = `-- name: ListAnalysisJobsByUserID :many
SELECT id, user_id,
       idempotency_key,
       car_make, car_model, car_generation, car_year,
       image_keys,
       correlation_id,
       status, error_message,
       result, used_model_version,
       requested_at, started_at, completed_at
FROM analysis_jobs
WHERE user_id = $1
ORDER BY requested_at DESC
    LIMIT $2 OFFSET $3
`

type ListAnalysisJobsByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListAnalysisJobsByUserID(ctx context.Context, arg ListAnalysisJobsByUserIDParams) ([]AnalysisJob, error) {
	rows, err := q.db.Query(ctx, listAnalysisJobsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalysisJob
	for rows.Next() {
		var i AnalysisJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IdempotencyKey,
			&i.CarMake,
			&i.CarModel,
			&i.CarGeneration,
			&i.CarYear,
			&i.ImageKeys,
			&i.CorrelationID,
			&i.Status,
			&i.ErrorMessage,
			&i.Result,
			&i.UsedModelVersion,
			&i.RequestedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnalysisJobResult = `-- name: UpdateAnalysisJobResult :execrows
UPDATE analysis_jobs
SET status = 'completed',
    result = $1,
    used_model_version = $2,
    completed_at = NOW()
WHERE id = $3
  AND status = 'pending'
`

type UpdateAnalysisJobResultParams struct {
	Result           []byte
	UsedModelVersion *string
	ID               pgtype.UUID
}

func (q *Queries) UpdateAnalysisJobResult(ctx context.Context, arg UpdateAnalysisJobResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAnalysisJobResult, arg.Result, arg.UsedModelVersion, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnalysisJobResultByCorrelationID = `-- name: UpdateAnalysisJobResultByCorrelationID :execrows
UPDATE analysis_jobs
SET status = 'completed',
    result = $1,
    used_model_version = $2,
    completed_at = NOW()
WHERE correlation_id = $3
  AND status = 'pending'
`

type UpdateAnalysisJobResultByCorrelationIDParams struct {
	Result           []byte
	UsedModelVersion *string
	CorrelationID    pgtype.UUID
}

func (q *Queries) UpdateAnalysisJobResultByCorrelationID(ctx context.Context, arg UpdateAnalysisJobResultByCorrelationIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAnalysisJobResultByCorrelationID, arg.Result, arg.UsedModelVersion, arg.CorrelationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnalysisJobStatus = `-- name: UpdateAnalysisJobStatus :execrows
UPDATE analysis_jobs
SET status = $1,
    error_message = $2,
    completed_at = CASE WHEN $1 IN ('completed', 'failed') THEN NOW() ELSE completed_at END
WHERE id = $3
  AND status = 'pending'
`

type UpdateAnalysisJobStatusParams struct {
	Status       string
	ErrorMessage *string
	ID           pgtype.UUID
}

func (q *Queries) UpdateAnalysisJobStatus(ctx context.Context, arg UpdateAnalysisJobStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAnalysisJobStatus, arg.Status, arg.ErrorMessage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnalysisJobStatusByCorrelationID = `-- name: UpdateAnalysisJobStatusByCorrelationID :execrows
UPDATE analysis_jobs
SET status = $1,
    error_message = $2,
    completed_at = CASE WHEN $1 IN ('completed', 'failed') THEN NOW() ELSE completed_at END
WHERE correlation_id = $3
  AND status = 'pending'
`

type UpdateAnalysisJobStatusByCorrelationIDParams struct {
	Status        string
	ErrorMessage  *string
	CorrelationID pgtype.UUID
}

func (q *Queries) UpdateAnalysisJobStatusByCorrelationID(ctx context.Context, arg UpdateAnalysisJobStatusByCorrelationIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAnalysisJobStatusByCorrelationID, arg.Status, arg.ErrorMessage, arg.CorrelationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
