// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: car_service_specializations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarServiceSpecialization = `-- name: CreateCarServiceSpecialization :exec
INSERT INTO car_service_specializations (
    id, profile_id, damage_type_code, part_category_code, created_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateCarServiceSpecializationParams struct {
	ID               pgtype.UUID
	ProfileID        pgtype.UUID
	DamageTypeCode   string
	PartCategoryCode string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCarServiceSpecialization(ctx context.Context, arg CreateCarServiceSpecializationParams) error {
	_, err := q.db.Exec(ctx, createCarServiceSpecialization,
		arg.ID,
		arg.ProfileID,
		arg.DamageTypeCode,
		arg.PartCategoryCode,
		arg.CreatedAt,
	)
	return err
}

const deleteCarServiceSpecializationsByProfileID = `-- name: DeleteCarServiceSpecializationsByProfileID :exec
DELETE FROM car_service_specializations
WHERE profile_id = $1
`

func (q *Queries) DeleteCarServiceSpecializationsByProfileID(ctx context.Context, profileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCarServiceSpecializationsByProfileID, profileID)
	return err
}

const existsActiveDamageType = `-- name: ExistsActiveDamageType :one
SELECT EXISTS(
    SELECT 1
    FROM damage_types
    WHERE code = $1
      AND is_active = TRUE
)::bool
`

func (q *Queries) ExistsActiveDamageType(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, existsActiveDamageType, code)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const existsActivePartCategory = `-- name: ExistsActivePartCategory :one
SELECT EXISTS(
    SELECT 1
    FROM part_categories
    WHERE code = $1
      AND is_active = TRUE
)::bool
`

func (q *Queries) ExistsActivePartCategory(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, existsActivePartCategory, code)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listActiveDamageTypes = `-- name: ListActiveDamageTypes :many
SELECT code, name_ru, is_active, created_at, updated_at
FROM damage_types
WHERE is_active = TRUE
ORDER BY name_ru ASC
`

func (q *Queries) ListActiveDamageTypes(ctx context.Context) ([]DamageType, error) {
	rows, err := q.db.Query(ctx, listActiveDamageTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DamageType
	for rows.Next() {
		var i DamageType
		if err := rows.Scan(
			&i.Code,
			&i.NameRu,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePartCategories = `-- name: ListActivePartCategories :many
SELECT code, name_ru, is_pair, is_active, created_at, updated_at
FROM part_categories
WHERE is_active = TRUE
ORDER BY CASE WHEN code = '*' THEN 0 ELSE 1 END, name_ru ASC
`

func (q *Queries) ListActivePartCategories(ctx context.Context) ([]PartCategory, error) {
	rows, err := q.db.Query(ctx, listActivePartCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartCategory
	for rows.Next() {
		var i PartCategory
		if err := rows.Scan(
			&i.Code,
			&i.NameRu,
			&i.IsPair,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDamageTypes = `-- name: ListAllDamageTypes :many
SELECT code, name_ru, is_active, created_at, updated_at
FROM damage_types
ORDER BY name_ru ASC
`

func (q *Queries) ListAllDamageTypes(ctx context.Context) ([]DamageType, error) {
	rows, err := q.db.Query(ctx, listAllDamageTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DamageType
	for rows.Next() {
		var i DamageType
		if err := rows.Scan(
			&i.Code,
			&i.NameRu,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarServiceSpecializationsByProfileID = `-- name: ListCarServiceSpecializationsByProfileID :many
SELECT id, profile_id, damage_type_code, part_category_code, created_at
FROM car_service_specializations
WHERE profile_id = $1
ORDER BY damage_type_code ASC, part_category_code ASC
`

func (q *Queries) ListCarServiceSpecializationsByProfileID(ctx context.Context, profileID pgtype.UUID) ([]CarServiceSpecialization, error) {
	rows, err := q.db.Query(ctx, listCarServiceSpecializationsByProfileID, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarServiceSpecialization
	for rows.Next() {
		var i CarServiceSpecialization
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.DamageTypeCode,
			&i.PartCategoryCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
