// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: car_service_matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMatchingCarServices = `-- name: ListMatchingCarServices :many
WITH criteria AS (
    SELECT
        unnest(CAST($3 AS text[])) AS damage_type_code,
        unnest(CAST($4 AS text[])) AS part_category_code
),
matched_profiles AS (
    SELECT
        p.id,
        p.user_id,
        p.organization_name,
        p.city,
        p.address,
        p.phone,
        p.email,
        p.website_url,
        p.contact_info,
        p.description,
        p.is_active,
        p.created_at,
        p.updated_at,
        COUNT(DISTINCT c.damage_type_code || '|' || c.part_category_code)::int AS match_count
    FROM car_service_profiles p
    JOIN car_service_specializations s ON s.profile_id = p.id
    JOIN criteria c ON c.damage_type_code = s.damage_type_code
       AND (c.part_category_code = s.part_category_code OR s.part_category_code = '*')
    WHERE p.is_active = TRUE
    GROUP BY p.id
)
SELECT
    mp.id,
    mp.user_id,
    mp.organization_name,
    mp.city,
    mp.address,
    mp.phone,
    mp.email,
    mp.website_url,
    mp.contact_info,
    mp.description,
    mp.is_active,
    mp.created_at,
    mp.updated_at,
    mp.match_count
FROM matched_profiles mp
ORDER BY mp.match_count DESC, mp.organization_name ASC
LIMIT $2 OFFSET $1
`

type ListMatchingCarServicesParams struct {
	Offset            int32
	Limit             int32
	DamageTypeCodes   []string
	PartCategoryCodes []string
}

type ListMatchingCarServicesRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	OrganizationName string
	City             string
	Address          string
	Phone            *string
	Email            *string
	WebsiteUrl       *string
	ContactInfo      *string
	Description      *string
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	MatchCount       int32
}

func (q *Queries) ListMatchingCarServices(ctx context.Context, arg ListMatchingCarServicesParams) ([]ListMatchingCarServicesRow, error) {
	rows, err := q.db.Query(ctx, listMatchingCarServices,
		arg.Offset,
		arg.Limit,
		arg.DamageTypeCodes,
		arg.PartCategoryCodes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchingCarServicesRow
	for rows.Next() {
		var i ListMatchingCarServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationName,
			&i.City,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.WebsiteUrl,
			&i.ContactInfo,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
