// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: car_service_images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPrimaryCarServiceImage = `-- name: ClearPrimaryCarServiceImage :exec
UPDATE car_service_images
SET is_primary = FALSE
WHERE profile_id = $1
  AND is_primary = TRUE
`

func (q *Queries) ClearPrimaryCarServiceImage(ctx context.Context, profileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryCarServiceImage, profileID)
	return err
}

const createCarServiceImage = `-- name: CreateCarServiceImage :exec
INSERT INTO car_service_images (
    id, profile_id, s3_key, is_primary, sort_order,
    original_filename, content_type, size_bytes, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type CreateCarServiceImageParams struct {
	ID               pgtype.UUID
	ProfileID        pgtype.UUID
	S3Key            string
	IsPrimary        bool
	SortOrder        int32
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCarServiceImage(ctx context.Context, arg CreateCarServiceImageParams) error {
	_, err := q.db.Exec(ctx, createCarServiceImage,
		arg.ID,
		arg.ProfileID,
		arg.S3Key,
		arg.IsPrimary,
		arg.SortOrder,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.CreatedAt,
	)
	return err
}

const deleteCarServiceImage = `-- name: DeleteCarServiceImage :execrows
DELETE FROM car_service_images
WHERE id = $1
`

func (q *Queries) DeleteCarServiceImage(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCarServiceImage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCarServiceImageByID = `-- name: GetCarServiceImageByID :one
SELECT id, profile_id, s3_key, is_primary, sort_order,
       original_filename, content_type, size_bytes, created_at
FROM car_service_images
WHERE id = $1
`

func (q *Queries) GetCarServiceImageByID(ctx context.Context, id pgtype.UUID) (CarServiceImage, error) {
	row := q.db.QueryRow(ctx, getCarServiceImageByID, id)
	var i CarServiceImage
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.S3Key,
		&i.IsPrimary,
		&i.SortOrder,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listCarServiceImagesByProfileID = `-- name: ListCarServiceImagesByProfileID :many
SELECT id, profile_id, s3_key, is_primary, sort_order,
       original_filename, content_type, size_bytes, created_at
FROM car_service_images
WHERE profile_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListCarServiceImagesByProfileID(ctx context.Context, profileID pgtype.UUID) ([]CarServiceImage, error) {
	rows, err := q.db.Query(ctx, listCarServiceImagesByProfileID, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarServiceImage
	for rows.Next() {
		var i CarServiceImage
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.S3Key,
			&i.IsPrimary,
			&i.SortOrder,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCarServiceImageSortOrder = `-- name: NextCarServiceImageSortOrder :one
SELECT COALESCE(MAX(sort_order), 0)::int + 1
FROM car_service_images
WHERE profile_id = $1
`

func (q *Queries) NextCarServiceImageSortOrder(ctx context.Context, profileID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextCarServiceImageSortOrder, profileID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setPrimaryCarServiceImage = `-- name: SetPrimaryCarServiceImage :execrows
UPDATE car_service_images
SET is_primary = TRUE
WHERE id = $1
`

func (q *Queries) SetPrimaryCarServiceImage(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setPrimaryCarServiceImage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
