// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: car_models.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarModel = `-- name: CreateCarModel :exec
INSERT INTO car_models (
    id, make, model, generation, year_from, year_to,
    parts_model_s3_key, parts_config_s3_key, parts_catalog_s3_key,
    model_version, is_universal, is_active, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateCarModelParams struct {
	ID                pgtype.UUID
	Make              string
	Model             string
	Generation        *string
	YearFrom          int32
	YearTo            *int32
	PartsModelS3Key   string
	PartsConfigS3Key  string
	PartsCatalogS3Key string
	ModelVersion      string
	IsUniversal       *bool
	IsActive          *bool
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateCarModel(ctx context.Context, arg CreateCarModelParams) error {
	_, err := q.db.Exec(ctx, createCarModel,
		arg.ID,
		arg.Make,
		arg.Model,
		arg.Generation,
		arg.YearFrom,
		arg.YearTo,
		arg.PartsModelS3Key,
		arg.PartsConfigS3Key,
		arg.PartsCatalogS3Key,
		arg.ModelVersion,
		arg.IsUniversal,
		arg.IsActive,
		arg.CreatedAt,
	)
	return err
}

const findActiveCarModel = `-- name: FindActiveCarModel :one
SELECT id, make, model, generation, year_from, year_to,
       parts_model_s3_key, parts_config_s3_key, parts_catalog_s3_key,
       model_version, is_universal, is_active, created_at
FROM car_models
WHERE is_active = true
  AND make = $1
  AND model = $2
  AND (generation = $3 OR generation = '' OR generation IS NULL)
  AND year_from <= $4
  AND (year_to >= $4 OR year_to IS NULL)
ORDER BY
    CASE WHEN generation = $3 THEN 0 ELSE 1 END,
    model_version DESC
LIMIT 1
`

type FindActiveCarModelParams struct {
	Make       string
	Model      string
	Generation *string
	YearFrom   int32
}

func (q *Queries) FindActiveCarModel(ctx context.Context, arg FindActiveCarModelParams) (CarModel, error) {
	row := q.db.QueryRow(ctx, findActiveCarModel,
		arg.Make,
		arg.Model,
		arg.Generation,
		arg.YearFrom,
	)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Generation,
		&i.YearFrom,
		&i.YearTo,
		&i.PartsModelS3Key,
		&i.PartsConfigS3Key,
		&i.PartsCatalogS3Key,
		&i.ModelVersion,
		&i.IsUniversal,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUniversalCarModel = `-- name: GetUniversalCarModel :one
SELECT id, make, model, generation, year_from, year_to,
       parts_model_s3_key, parts_config_s3_key, parts_catalog_s3_key,
       model_version, is_universal, is_active, created_at
FROM car_models
WHERE is_active = true
  AND is_universal = true
    LIMIT 1
`

func (q *Queries) GetUniversalCarModel(ctx context.Context) (CarModel, error) {
	row := q.db.QueryRow(ctx, getUniversalCarModel)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Generation,
		&i.YearFrom,
		&i.YearTo,
		&i.PartsModelS3Key,
		&i.PartsConfigS3Key,
		&i.PartsCatalogS3Key,
		&i.ModelVersion,
		&i.IsUniversal,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
