// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: car_service_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarServiceProfile = `-- name: CreateCarServiceProfile :exec
INSERT INTO car_service_profiles (
    id, user_id,
    organization_name, city, address, phone, email, website_url, contact_info, description,
    is_active, created_at, updated_at
) VALUES (
    $1, $2,
    $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13
)
`

type CreateCarServiceProfileParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	OrganizationName string
	City             string
	Address          string
	Phone            *string
	Email            *string
	WebsiteUrl       *string
	ContactInfo      *string
	Description      *string
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCarServiceProfile(ctx context.Context, arg CreateCarServiceProfileParams) error {
	_, err := q.db.Exec(ctx, createCarServiceProfile,
		arg.ID,
		arg.UserID,
		arg.OrganizationName,
		arg.City,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.WebsiteUrl,
		arg.ContactInfo,
		arg.Description,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getCarServiceProfileByID = `-- name: GetCarServiceProfileByID :one
SELECT id, user_id,
       organization_name, city, address, phone, email, website_url, contact_info, description,
       is_active, created_at, updated_at
FROM car_service_profiles
WHERE id = $1
`

func (q *Queries) GetCarServiceProfileByID(ctx context.Context, id pgtype.UUID) (CarServiceProfile, error) {
	row := q.db.QueryRow(ctx, getCarServiceProfileByID, id)
	var i CarServiceProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationName,
		&i.City,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.WebsiteUrl,
		&i.ContactInfo,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarServiceProfileByUserID = `-- name: GetCarServiceProfileByUserID :one
SELECT id, user_id,
       organization_name, city, address, phone, email, website_url, contact_info, description,
       is_active, created_at, updated_at
FROM car_service_profiles
WHERE user_id = $1
`

func (q *Queries) GetCarServiceProfileByUserID(ctx context.Context, userID pgtype.UUID) (CarServiceProfile, error) {
	row := q.db.QueryRow(ctx, getCarServiceProfileByUserID, userID)
	var i CarServiceProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationName,
		&i.City,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.WebsiteUrl,
		&i.ContactInfo,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCarServiceProfileActive = `-- name: SetCarServiceProfileActive :execrows
UPDATE car_service_profiles
SET is_active = $2,
    updated_at = $3
WHERE user_id = $1
`

type SetCarServiceProfileActiveParams struct {
	UserID    pgtype.UUID
	IsActive  bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetCarServiceProfileActive(ctx context.Context, arg SetCarServiceProfileActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCarServiceProfileActive, arg.UserID, arg.IsActive, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCarServiceProfile = `-- name: UpdateCarServiceProfile :execrows
UPDATE car_service_profiles
SET organization_name = $2,
    city = $3,
    address = $4,
    phone = $5,
    email = $6,
    website_url = $7,
    contact_info = $8,
    description = $9,
    is_active = $10,
    updated_at = $11
WHERE user_id = $1
`

type UpdateCarServiceProfileParams struct {
	UserID           pgtype.UUID
	OrganizationName string
	City             string
	Address          string
	Phone            *string
	Email            *string
	WebsiteUrl       *string
	ContactInfo      *string
	Description      *string
	IsActive         bool
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateCarServiceProfile(ctx context.Context, arg UpdateCarServiceProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCarServiceProfile,
		arg.UserID,
		arg.OrganizationName,
		arg.City,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.WebsiteUrl,
		arg.ContactInfo,
		arg.Description,
		arg.IsActive,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
