// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: car_models.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarModel = `-- name: CreateCarModel :exec
INSERT INTO car_models (
    id, make, model, generation, year_from, year_to,
    parts_model_s3_key, parts_config_s3_key, parts_catalog_s3_key,
    model_version, is_universal, is_active, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateCarModelParams struct {
	ID                pgtype.UUID
	Make              string
	Model             string
	Generation        *string
	YearFrom          int32
	YearTo            *int32
	PartsModelS3Key   string
	PartsConfigS3Key  string
	PartsCatalogS3Key string
	ModelVersion      string
	IsUniversal       *bool
	IsActive          *bool
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateCarModel(ctx context.Context, arg CreateCarModelParams) error {
	_, err := q.db.Exec(ctx, createCarModel,
		arg.ID,
		arg.Make,
		arg.Model,
		arg.Generation,
		arg.YearFrom,
		arg.YearTo,
		arg.PartsModelS3Key,
		arg.PartsConfigS3Key,
		arg.PartsCatalogS3Key,
		arg.ModelVersion,
		arg.IsUniversal,
		arg.IsActive,
		arg.CreatedAt,
	)
	return err
}

const deactivateCarModel = `-- name: DeactivateCarModel :exec
UPDATE car_models
SET is_active = false
WHERE id = $1
`

func (q *Queries) DeactivateCarModel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateCarModel, id)
	return err
}

const findActiveCarModel = `-- name: FindActiveCarModel :one
SELECT id, make, model, generation, year_from, year_to,
       parts_model_s3_key, parts_config_s3_key, parts_catalog_s3_key,
       model_version, is_universal, is_active, created_at
FROM car_models
WHERE is_active = true
  AND make = $1
  AND model = $2
  AND (generation = $3 OR generation = '' OR generation IS NULL)
  AND year_from <= $4
  AND (year_to >= $4 OR year_to IS NULL)
ORDER BY
    CASE WHEN generation = $3 THEN 0 ELSE 1 END,
    model_version DESC
LIMIT 1
`

type FindActiveCarModelParams struct {
	Make       string
	Model      string
	Generation *string
	YearFrom   int32
}

func (q *Queries) FindActiveCarModel(ctx context.Context, arg FindActiveCarModelParams) (CarModel, error) {
	row := q.db.QueryRow(ctx, findActiveCarModel,
		arg.Make,
		arg.Model,
		arg.Generation,
		arg.YearFrom,
	)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Generation,
		&i.YearFrom,
		&i.YearTo,
		&i.PartsModelS3Key,
		&i.PartsConfigS3Key,
		&i.PartsCatalogS3Key,
		&i.ModelVersion,
		&i.IsUniversal,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCarModelByID = `-- name: GetCarModelByID :one
SELECT id, make, model, generation, year_from, year_to,
       parts_model_s3_key, parts_config_s3_key, parts_catalog_s3_key,
       model_version, is_universal, is_active, created_at
FROM car_models
WHERE id = $1
`

func (q *Queries) GetCarModelByID(ctx context.Context, id pgtype.UUID) (CarModel, error) {
	row := q.db.QueryRow(ctx, getCarModelByID, id)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Generation,
		&i.YearFrom,
		&i.YearTo,
		&i.PartsModelS3Key,
		&i.PartsConfigS3Key,
		&i.PartsCatalogS3Key,
		&i.ModelVersion,
		&i.IsUniversal,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUniversalCarModel = `-- name: GetUniversalCarModel :one
SELECT id, make, model, generation, year_from, year_to,
       parts_model_s3_key, parts_config_s3_key, parts_catalog_s3_key,
       model_version, is_universal, is_active, created_at
FROM car_models
WHERE is_active = true
  AND is_universal = true
    LIMIT 1
`

func (q *Queries) GetUniversalCarModel(ctx context.Context) (CarModel, error) {
	row := q.db.QueryRow(ctx, getUniversalCarModel)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Generation,
		&i.YearFrom,
		&i.YearTo,
		&i.PartsModelS3Key,
		&i.PartsConfigS3Key,
		&i.PartsCatalogS3Key,
		&i.ModelVersion,
		&i.IsUniversal,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCarModels = `-- name: ListCarModels :many
SELECT id, make, model, generation, year_from, year_to,
       parts_model_s3_key, parts_config_s3_key, parts_catalog_s3_key,
       model_version, is_universal, is_active, created_at
FROM car_models
ORDER BY created_at DESC
    LIMIT $1 OFFSET $2
`

type ListCarModelsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCarModels(ctx context.Context, arg ListCarModelsParams) ([]CarModel, error) {
	rows, err := q.db.Query(ctx, listCarModels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarModel
	for rows.Next() {
		var i CarModel
		if err := rows.Scan(
			&i.ID,
			&i.Make,
			&i.Model,
			&i.Generation,
			&i.YearFrom,
			&i.YearTo,
			&i.PartsModelS3Key,
			&i.PartsConfigS3Key,
			&i.PartsCatalogS3Key,
			&i.ModelVersion,
			&i.IsUniversal,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
