// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: car_service_applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarServiceApplication = `-- name: CreateCarServiceApplication :exec
INSERT INTO car_service_applications (
    id, user_id,
    organization_name, city, address, phone, email, contact_info, description,
    status, rejection_reason, reviewed_by, reviewed_at, created_profile_id,
    created_at, updated_at
) VALUES (
    $1, $2,
    $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16
)
`

type CreateCarServiceApplicationParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	OrganizationName string
	City             string
	Address          string
	Phone            *string
	Email            *string
	ContactInfo      *string
	Description      string
	Status           string
	RejectionReason  *string
	ReviewedBy       pgtype.UUID
	ReviewedAt       pgtype.Timestamptz
	CreatedProfileID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCarServiceApplication(ctx context.Context, arg CreateCarServiceApplicationParams) error {
	_, err := q.db.Exec(ctx, createCarServiceApplication,
		arg.ID,
		arg.UserID,
		arg.OrganizationName,
		arg.City,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ContactInfo,
		arg.Description,
		arg.Status,
		arg.RejectionReason,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.CreatedProfileID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getCarServiceApplicationByID = `-- name: GetCarServiceApplicationByID :one
SELECT id, user_id,
       organization_name, city, address, phone, email, contact_info, description,
       status, rejection_reason, reviewed_by, reviewed_at, created_profile_id,
       created_at, updated_at
FROM car_service_applications
WHERE id = $1
`

func (q *Queries) GetCarServiceApplicationByID(ctx context.Context, id pgtype.UUID) (CarServiceApplication, error) {
	row := q.db.QueryRow(ctx, getCarServiceApplicationByID, id)
	var i CarServiceApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationName,
		&i.City,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactInfo,
		&i.Description,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingCarServiceApplicationByUserID = `-- name: GetPendingCarServiceApplicationByUserID :one
SELECT id, user_id,
       organization_name, city, address, phone, email, contact_info, description,
       status, rejection_reason, reviewed_by, reviewed_at, created_profile_id,
       created_at, updated_at
FROM car_service_applications
WHERE user_id = $1
  AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingCarServiceApplicationByUserID(ctx context.Context, userID pgtype.UUID) (CarServiceApplication, error) {
	row := q.db.QueryRow(ctx, getPendingCarServiceApplicationByUserID, userID)
	var i CarServiceApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationName,
		&i.City,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactInfo,
		&i.Description,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCarServiceApplicationsByUserID = `-- name: ListCarServiceApplicationsByUserID :many
SELECT id, user_id,
       organization_name, city, address, phone, email, contact_info, description,
       status, rejection_reason, reviewed_by, reviewed_at, created_profile_id,
       created_at, updated_at
FROM car_service_applications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCarServiceApplicationsByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListCarServiceApplicationsByUserID(ctx context.Context, arg ListCarServiceApplicationsByUserIDParams) ([]CarServiceApplication, error) {
	rows, err := q.db.Query(ctx, listCarServiceApplicationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarServiceApplication
	for rows.Next() {
		var i CarServiceApplication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationName,
			&i.City,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactInfo,
			&i.Description,
			&i.Status,
			&i.RejectionReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedProfileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
