// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: car_service_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarServiceReview = `-- name: CreateCarServiceReview :exec
INSERT INTO car_service_reviews (
    id, repair_request_id, car_service_profile_id, user_id,
    rating, author_name, comment,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
`

type CreateCarServiceReviewParams struct {
	ID                  pgtype.UUID
	RepairRequestID     pgtype.UUID
	CarServiceProfileID pgtype.UUID
	UserID              pgtype.UUID
	Rating              int32
	AuthorName          *string
	Comment             *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateCarServiceReview(ctx context.Context, arg CreateCarServiceReviewParams) error {
	_, err := q.db.Exec(ctx, createCarServiceReview,
		arg.ID,
		arg.RepairRequestID,
		arg.CarServiceProfileID,
		arg.UserID,
		arg.Rating,
		arg.AuthorName,
		arg.Comment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCarServiceReviewByRepairRequestIDAndUserID = `-- name: DeleteCarServiceReviewByRepairRequestIDAndUserID :execrows
DELETE FROM car_service_reviews
WHERE repair_request_id = $1
  AND user_id = $2
`

type DeleteCarServiceReviewByRepairRequestIDAndUserIDParams struct {
	RepairRequestID pgtype.UUID
	UserID          pgtype.UUID
}

func (q *Queries) DeleteCarServiceReviewByRepairRequestIDAndUserID(ctx context.Context, arg DeleteCarServiceReviewByRepairRequestIDAndUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCarServiceReviewByRepairRequestIDAndUserID, arg.RepairRequestID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCarServiceReviewByID = `-- name: GetCarServiceReviewByID :one
SELECT id, repair_request_id, car_service_profile_id, user_id,
       rating, author_name, comment,
       created_at, updated_at
FROM car_service_reviews
WHERE id = $1
`

func (q *Queries) GetCarServiceReviewByID(ctx context.Context, id pgtype.UUID) (CarServiceReview, error) {
	row := q.db.QueryRow(ctx, getCarServiceReviewByID, id)
	var i CarServiceReview
	err := row.Scan(
		&i.ID,
		&i.RepairRequestID,
		&i.CarServiceProfileID,
		&i.UserID,
		&i.Rating,
		&i.AuthorName,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarServiceReviewByRepairRequestID = `-- name: GetCarServiceReviewByRepairRequestID :one
SELECT id, repair_request_id, car_service_profile_id, user_id,
       rating, author_name, comment,
       created_at, updated_at
FROM car_service_reviews
WHERE repair_request_id = $1
`

func (q *Queries) GetCarServiceReviewByRepairRequestID(ctx context.Context, repairRequestID pgtype.UUID) (CarServiceReview, error) {
	row := q.db.QueryRow(ctx, getCarServiceReviewByRepairRequestID, repairRequestID)
	var i CarServiceReview
	err := row.Scan(
		&i.ID,
		&i.RepairRequestID,
		&i.CarServiceProfileID,
		&i.UserID,
		&i.Rating,
		&i.AuthorName,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCarServiceReviewsByProfileID = `-- name: ListCarServiceReviewsByProfileID :many
SELECT id, repair_request_id, car_service_profile_id, user_id,
       rating, author_name, comment,
       created_at, updated_at
FROM car_service_reviews
WHERE car_service_profile_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCarServiceReviewsByProfileIDParams struct {
	CarServiceProfileID pgtype.UUID
	Limit               int32
	Offset              int32
}

func (q *Queries) ListCarServiceReviewsByProfileID(ctx context.Context, arg ListCarServiceReviewsByProfileIDParams) ([]CarServiceReview, error) {
	rows, err := q.db.Query(ctx, listCarServiceReviewsByProfileID, arg.CarServiceProfileID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarServiceReview
	for rows.Next() {
		var i CarServiceReview
		if err := rows.Scan(
			&i.ID,
			&i.RepairRequestID,
			&i.CarServiceProfileID,
			&i.UserID,
			&i.Rating,
			&i.AuthorName,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarServiceReviewsByUserID = `-- name: ListCarServiceReviewsByUserID :many
SELECT id, repair_request_id, car_service_profile_id, user_id,
       rating, author_name, comment,
       created_at, updated_at
FROM car_service_reviews
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCarServiceReviewsByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListCarServiceReviewsByUserID(ctx context.Context, arg ListCarServiceReviewsByUserIDParams) ([]CarServiceReview, error) {
	rows, err := q.db.Query(ctx, listCarServiceReviewsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarServiceReview
	for rows.Next() {
		var i CarServiceReview
		if err := rows.Scan(
			&i.ID,
			&i.RepairRequestID,
			&i.CarServiceProfileID,
			&i.UserID,
			&i.Rating,
			&i.AuthorName,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCarServiceReviewByRepairRequestIDAndUserID = `-- name: UpdateCarServiceReviewByRepairRequestIDAndUserID :one
UPDATE car_service_reviews
SET rating = $3,
    author_name = $4,
    comment = $5
WHERE repair_request_id = $1
  AND user_id = $2
RETURNING id, repair_request_id, car_service_profile_id, user_id,
          rating, author_name, comment,
          created_at, updated_at
`

type UpdateCarServiceReviewByRepairRequestIDAndUserIDParams struct {
	RepairRequestID pgtype.UUID
	UserID          pgtype.UUID
	Rating          int32
	AuthorName      *string
	Comment         *string
}

func (q *Queries) UpdateCarServiceReviewByRepairRequestIDAndUserID(ctx context.Context, arg UpdateCarServiceReviewByRepairRequestIDAndUserIDParams) (CarServiceReview, error) {
	row := q.db.QueryRow(ctx, updateCarServiceReviewByRepairRequestIDAndUserID,
		arg.RepairRequestID,
		arg.UserID,
		arg.Rating,
		arg.AuthorName,
		arg.Comment,
	)
	var i CarServiceReview
	err := row.Scan(
		&i.ID,
		&i.RepairRequestID,
		&i.CarServiceProfileID,
		&i.UserID,
		&i.Rating,
		&i.AuthorName,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
