// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// Асинхронные задачи анализа изображений и результаты ML
type AnalysisJob struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	IdempotencyKey   *string
	CarMake          *string
	CarModel         *string
	CarGeneration    *string
	CarYear          *int32
	ImageKeys        []byte
	CorrelationID    pgtype.UUID
	Status           string
	ErrorMessage     *string
	Result           []byte
	UsedModelVersion *string
	RequestedAt      pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

// Таблица для хранения связей между пользователями и их OAuth-учетными записями (Google, Facebook и т.д.)
type AuthOauthIdentity struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          *string
	CreatedAt      pgtype.Timestamptz
}

// Таблица для хранения сессий пользователей, поддерживающая механизмы замены и отзыва токенов
type AuthSession struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	TokenHash     string
	TokenFamilyID pgtype.UUID
	ReplacedByID  pgtype.UUID
	UserAgent     *string
	IpAddress     *netip.Addr
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedReason *string
	LastUsedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Реестр моделей сегментации деталей и связанных ML-артефактов
type CarModel struct {
	ID                pgtype.UUID
	Make              string
	Model             string
	Generation        *string
	YearFrom          int32
	YearTo            *int32
	PartsModelS3Key   string
	PartsConfigS3Key  string
	PartsCatalogS3Key string
	ModelVersion      string
	IsUniversal       *bool
	IsActive          *bool
	CreatedAt         pgtype.Timestamptz
}

// Заявки пользователей на получение роли автосервиса
type CarServiceApplication struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	OrganizationName string
	City             string
	Address          string
	Phone            *string
	Email            *string
	ContactInfo      *string
	Description      string
	Status           string
	RejectionReason  *string
	ReviewedBy       pgtype.UUID
	ReviewedAt       pgtype.Timestamptz
	CreatedProfileID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Изображения профилей автосервисов, хранящиеся в MinIO
type CarServiceImage struct {
	ID               pgtype.UUID
	ProfileID        pgtype.UUID
	S3Key            string
	IsPrimary        bool
	SortOrder        int32
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	CreatedAt        pgtype.Timestamptz
}

// Профили автосервисов, созданные после одобрения заявки пользователя
type CarServiceProfile struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	OrganizationName string
	City             string
	Address          string
	Phone            *string
	Email            *string
	WebsiteUrl       *string
	ContactInfo      *string
	Description      *string
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Специализации автосервисов по типам повреждений и категориям деталей
type CarServiceSpecialization struct {
	ID               pgtype.UUID
	ProfileID        pgtype.UUID
	DamageTypeCode   string
	PartCategoryCode string
	CreatedAt        pgtype.Timestamptz
}

// Справочник типов повреждений, соответствующих результатам ML-сервиса
type DamageType struct {
	Code      string
	NameRu    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Заявки пользователей на добавление или обучение моделей сегментации деталей
type ModelTrainingRequest struct {
	ID              pgtype.UUID
	InitiatorUserID pgtype.UUID
	InitiatorRole   string
	Make            string
	Model           string
	Generation      *string
	YearFrom        int32
	YearTo          *int32
	Description     string
	Status          string
	AdminComment    *string
	ReviewedBy      pgtype.UUID
	ReviewedAt      pgtype.Timestamptz
	CreatedModelID  pgtype.UUID
	IdempotencyKey  *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Справочник обобщённых категорий деталей автомобиля для специализации автосервисов
type PartCategory struct {
	Code      string
	NameRu    string
	IsPair    bool
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Заявки пользователей на ремонт автомобиля по результатам анализа
type RepairRequest struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	AnalysisJobID       pgtype.UUID
	CarServiceProfileID pgtype.UUID
	Status              string
	// Снимок ремонтной сводки, сформированной из результата анализа на момент создания заявки
	RepairSummary []byte
	// Предварительная смета автосервиса по парам деталь и тип повреждения
	ServiceEstimate   []byte
	CustomerName      *string
	CustomerPhone     *string
	CustomerEmail     *string
	CustomerComment   *string
	ServiceComment    *string
	EstimatedPriceMin pgtype.Numeric
	EstimatedPriceMax pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RespondedAt       pgtype.Timestamptz
}

// Таблица для хранения информации о пользователях, включая аутентификацию и роли
type User struct {
	ID            pgtype.UUID
	Username      string
	Email         string
	AvatarUrl     *string
	PasswordHash  string
	Role          string
	EmailVerified *bool
	IsActive      *bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	LastLogin     pgtype.Timestamptz
}
