// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_training_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveModelTrainingRequestsByUserID = `-- name: CountActiveModelTrainingRequestsByUserID :one
SELECT count(*)::int
FROM model_training_requests
WHERE initiator_user_id = $1
  AND status IN ('pending', 'approved', 'in_progress')
`

func (q *Queries) CountActiveModelTrainingRequestsByUserID(ctx context.Context, initiatorUserID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveModelTrainingRequestsByUserID, initiatorUserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createModelTrainingRequest = `-- name: CreateModelTrainingRequest :exec
INSERT INTO model_training_requests (
    id, initiator_user_id, initiator_role,
    make, model, generation, year_from, year_to, description,
    status, admin_comment, reviewed_by, reviewed_at,
    created_model_id, idempotency_key, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17
)
`

type CreateModelTrainingRequestParams struct {
	ID              pgtype.UUID
	InitiatorUserID pgtype.UUID
	InitiatorRole   string
	Make            string
	Model           string
	Generation      *string
	YearFrom        int32
	YearTo          *int32
	Description     string
	Status          string
	AdminComment    *string
	ReviewedBy      pgtype.UUID
	ReviewedAt      pgtype.Timestamptz
	CreatedModelID  pgtype.UUID
	IdempotencyKey  *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateModelTrainingRequest(ctx context.Context, arg CreateModelTrainingRequestParams) error {
	_, err := q.db.Exec(ctx, createModelTrainingRequest,
		arg.ID,
		arg.InitiatorUserID,
		arg.InitiatorRole,
		arg.Make,
		arg.Model,
		arg.Generation,
		arg.YearFrom,
		arg.YearTo,
		arg.Description,
		arg.Status,
		arg.AdminComment,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.CreatedModelID,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getModelTrainingRequestByID = `-- name: GetModelTrainingRequestByID :one
SELECT id, initiator_user_id, initiator_role,
       make, model, generation, year_from, year_to, description,
       status, admin_comment, reviewed_by, reviewed_at,
       created_model_id, idempotency_key, created_at, updated_at
FROM model_training_requests
WHERE id = $1
`

func (q *Queries) GetModelTrainingRequestByID(ctx context.Context, id pgtype.UUID) (ModelTrainingRequest, error) {
	row := q.db.QueryRow(ctx, getModelTrainingRequestByID, id)
	var i ModelTrainingRequest
	err := row.Scan(
		&i.ID,
		&i.InitiatorUserID,
		&i.InitiatorRole,
		&i.Make,
		&i.Model,
		&i.Generation,
		&i.YearFrom,
		&i.YearTo,
		&i.Description,
		&i.Status,
		&i.AdminComment,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedModelID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelTrainingRequestByUserAndIdempotencyKey = `-- name: GetModelTrainingRequestByUserAndIdempotencyKey :one
SELECT id, initiator_user_id, initiator_role,
       make, model, generation, year_from, year_to, description,
       status, admin_comment, reviewed_by, reviewed_at,
       created_model_id, idempotency_key, created_at, updated_at
FROM model_training_requests
WHERE initiator_user_id = $1
  AND idempotency_key = $2
`

type GetModelTrainingRequestByUserAndIdempotencyKeyParams struct {
	InitiatorUserID pgtype.UUID
	IdempotencyKey  *string
}

func (q *Queries) GetModelTrainingRequestByUserAndIdempotencyKey(ctx context.Context, arg GetModelTrainingRequestByUserAndIdempotencyKeyParams) (ModelTrainingRequest, error) {
	row := q.db.QueryRow(ctx, getModelTrainingRequestByUserAndIdempotencyKey, arg.InitiatorUserID, arg.IdempotencyKey)
	var i ModelTrainingRequest
	err := row.Scan(
		&i.ID,
		&i.InitiatorUserID,
		&i.InitiatorRole,
		&i.Make,
		&i.Model,
		&i.Generation,
		&i.YearFrom,
		&i.YearTo,
		&i.Description,
		&i.Status,
		&i.AdminComment,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedModelID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelTrainingRequestsByUserID = `-- name: ListModelTrainingRequestsByUserID :many
SELECT id, initiator_user_id, initiator_role,
       make, model, generation, year_from, year_to, description,
       status, admin_comment, reviewed_by, reviewed_at,
       created_model_id, idempotency_key, created_at, updated_at
FROM model_training_requests
WHERE initiator_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListModelTrainingRequestsByUserIDParams struct {
	InitiatorUserID pgtype.UUID
	Limit           int32
	Offset          int32
}

func (q *Queries) ListModelTrainingRequestsByUserID(ctx context.Context, arg ListModelTrainingRequestsByUserIDParams) ([]ModelTrainingRequest, error) {
	rows, err := q.db.Query(ctx, listModelTrainingRequestsByUserID, arg.InitiatorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelTrainingRequest
	for rows.Next() {
		var i ModelTrainingRequest
		if err := rows.Scan(
			&i.ID,
			&i.InitiatorUserID,
			&i.InitiatorRole,
			&i.Make,
			&i.Model,
			&i.Generation,
			&i.YearFrom,
			&i.YearTo,
			&i.Description,
			&i.Status,
			&i.AdminComment,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedModelID,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelTrainingRequestsForAdmin = `-- name: ListModelTrainingRequestsForAdmin :many
SELECT id, initiator_user_id, initiator_role,
       make, model, generation, year_from, year_to, description,
       status, admin_comment, reviewed_by, reviewed_at,
       created_model_id, idempotency_key, created_at, updated_at
FROM model_training_requests
WHERE $3::text IS NULL
   OR status = $3::text
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListModelTrainingRequestsForAdminParams struct {
	Limit  int32
	Offset int32
	Status *string
}

func (q *Queries) ListModelTrainingRequestsForAdmin(ctx context.Context, arg ListModelTrainingRequestsForAdminParams) ([]ModelTrainingRequest, error) {
	rows, err := q.db.Query(ctx, listModelTrainingRequestsForAdmin, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelTrainingRequest
	for rows.Next() {
		var i ModelTrainingRequest
		if err := rows.Scan(
			&i.ID,
			&i.InitiatorUserID,
			&i.InitiatorRole,
			&i.Make,
			&i.Model,
			&i.Generation,
			&i.YearFrom,
			&i.YearTo,
			&i.Description,
			&i.Status,
			&i.AdminComment,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedModelID,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelTrainingRequestStatus = `-- name: UpdateModelTrainingRequestStatus :execrows
UPDATE model_training_requests
SET status = $2,
    admin_comment = $3,
    reviewed_by = $4,
    reviewed_at = $5,
    created_model_id = $6,
    updated_at = $7
WHERE id = $1
`

type UpdateModelTrainingRequestStatusParams struct {
	ID             pgtype.UUID
	Status         string
	AdminComment   *string
	ReviewedBy     pgtype.UUID
	ReviewedAt     pgtype.Timestamptz
	CreatedModelID pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateModelTrainingRequestStatus(ctx context.Context, arg UpdateModelTrainingRequestStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelTrainingRequestStatus,
		arg.ID,
		arg.Status,
		arg.AdminComment,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.CreatedModelID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
