// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Analysis struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Status        string
	CarMake       string
	CarModel      string
	CarGeneration *string
	CarYear       *int32
	ImageKey      string
	ImageMetadata []byte
	ModelVersion  *string
	ModelID       pgtype.UUID
	ResultJson    []byte
	ErrorMessage  *string
	ErrorCode     *string
	RetryCount    *int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}

type AuditLog struct {
	ID         int64
	UserID     pgtype.UUID
	Action     string
	EntityType *string
	EntityID   pgtype.UUID
	IpAddress  *netip.Addr
	UserAgent  *string
	RequestID  pgtype.UUID
	Details    []byte
	StatusCode *int32
	CreatedAt  pgtype.Timestamptz
}

type AuthOauthIdentity struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          *string
	CreatedAt      pgtype.Timestamptz
}

type AuthSession struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	TokenHash     string
	TokenFamilyID pgtype.UUID
	ReplacedByID  pgtype.UUID
	UserAgent     *string
	IpAddress     *netip.Addr
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedReason *string
	LastUsedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Model struct {
	ID            pgtype.UUID
	Version       string
	Name          string
	CarMake       string
	CarModel      string
	CarGeneration *string
	YearFrom      *int32
	YearTo        *int32
	WeightsPath   string
	ConfigPath    *string
	Status        string
	Active        bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Username      string
	Email         string
	PasswordHash  string
	Role          string
	EmailVerified *bool
	IsActive      *bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	LastLogin     pgtype.Timestamptz
}
