// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// Асинхронные задачи анализа изображений и результаты ML
type AnalysisJob struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	IdempotencyKey   *string
	CarMake          *string
	CarModel         *string
	CarGeneration    *string
	CarYear          *int32
	ImageKeys        []byte
	CorrelationID    pgtype.UUID
	Status           string
	ErrorMessage     *string
	Result           []byte
	UsedModelVersion *string
	RequestedAt      pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

type AuthOauthIdentity struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          *string
	CreatedAt      pgtype.Timestamptz
}

type AuthSession struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	TokenHash     string
	TokenFamilyID pgtype.UUID
	ReplacedByID  pgtype.UUID
	UserAgent     *string
	IpAddress     *netip.Addr
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedReason *string
	LastUsedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Реестр ML-моделей, привязанных к маркам/моделям/годам авто
type CarModel struct {
	ID           pgtype.UUID
	Make         string
	Model        string
	Generation   *string
	YearFrom     int32
	YearTo       *int32
	ModelS3Key   string
	ModelVersion string
	IsUniversal  *bool
	IsActive     *bool
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Username      string
	Email         string
	PasswordHash  string
	Role          string
	EmailVerified *bool
	IsActive      *bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	LastLogin     pgtype.Timestamptz
}
