// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :exec
INSERT INTO auth_oauth_identities (id, user_id, provider, provider_user_id, email, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOAuthIdentityParams struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          *string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const getOAuthIdentityByProviderSubject = `-- name: GetOAuthIdentityByProviderSubject :one
SELECT id, user_id, provider, provider_user_id, email, created_at
FROM auth_oauth_identities
WHERE provider = $1 AND provider_user_id = $2
    LIMIT 1
`

type GetOAuthIdentityByProviderSubjectParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetOAuthIdentityByProviderSubject(ctx context.Context, arg GetOAuthIdentityByProviderSubjectParams) (AuthOauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityByProviderSubject, arg.Provider, arg.ProviderUserID)
	var i AuthOauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
