// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveCarServiceApplication(ctx context.Context, arg ApproveCarServiceApplicationParams) (int64, error)
	CancelPendingRepairRequestByUserID(ctx context.Context, arg CancelPendingRepairRequestByUserIDParams) (int64, error)
	ClearPrimaryCarServiceImage(ctx context.Context, profileID pgtype.UUID) error
	CompleteAcceptedRepairRequestByCarServiceProfileID(ctx context.Context, arg CompleteAcceptedRepairRequestByCarServiceProfileIDParams) (int64, error)
	CountActiveModelTrainingRequestsByUserID(ctx context.Context, initiatorUserID pgtype.UUID) (int32, error)
	CreateAnalysisJob(ctx context.Context, arg CreateAnalysisJobParams) error
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error
	CreateCarModel(ctx context.Context, arg CreateCarModelParams) error
	CreateCarServiceApplication(ctx context.Context, arg CreateCarServiceApplicationParams) error
	CreateCarServiceImage(ctx context.Context, arg CreateCarServiceImageParams) error
	CreateCarServiceProfile(ctx context.Context, arg CreateCarServiceProfileParams) error
	CreateCarServiceReview(ctx context.Context, arg CreateCarServiceReviewParams) error
	CreateCarServiceSpecialization(ctx context.Context, arg CreateCarServiceSpecializationParams) error
	CreateModelTrainingRequest(ctx context.Context, arg CreateModelTrainingRequestParams) error
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error
	CreateRepairRequest(ctx context.Context, arg CreateRepairRequestParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateVehicleGeneration(ctx context.Context, arg CreateVehicleGenerationParams) error
	CreateVehicleMake(ctx context.Context, arg CreateVehicleMakeParams) error
	CreateVehicleModel(ctx context.Context, arg CreateVehicleModelParams) error
	DeactivateCarModel(ctx context.Context, id pgtype.UUID) error
	DeleteCarServiceImage(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteCarServiceReviewByRepairRequestIDAndUserID(ctx context.Context, arg DeleteCarServiceReviewByRepairRequestIDAndUserIDParams) (int64, error)
	DeleteCarServiceSpecializationsByProfileID(ctx context.Context, profileID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	ExistsActiveDamageType(ctx context.Context, code string) (bool, error)
	ExistsActivePartCategory(ctx context.Context, code string) (bool, error)
	FindActiveCarModel(ctx context.Context, arg FindActiveCarModelParams) (CarModel, error)
	GetAnalysisJobByCorrelationID(ctx context.Context, correlationID pgtype.UUID) (AnalysisJob, error)
	GetAnalysisJobByID(ctx context.Context, id pgtype.UUID) (AnalysisJob, error)
	GetAnalysisJobByUserAndIdempotencyKey(ctx context.Context, arg GetAnalysisJobByUserAndIdempotencyKeyParams) (AnalysisJob, error)
	GetAuthSessionByTokenHash(ctx context.Context, tokenHash string) (AuthSession, error)
	GetCarModelByID(ctx context.Context, id pgtype.UUID) (CarModel, error)
	GetCarServiceApplicationByID(ctx context.Context, id pgtype.UUID) (CarServiceApplication, error)
	GetCarServiceImageByID(ctx context.Context, id pgtype.UUID) (CarServiceImage, error)
	GetCarServiceProfileByID(ctx context.Context, id pgtype.UUID) (CarServiceProfile, error)
	GetCarServiceProfileByUserID(ctx context.Context, userID pgtype.UUID) (CarServiceProfile, error)
	GetCarServiceReviewByID(ctx context.Context, id pgtype.UUID) (CarServiceReview, error)
	GetCarServiceReviewByRepairRequestID(ctx context.Context, repairRequestID pgtype.UUID) (CarServiceReview, error)
	GetModelTrainingRequestByID(ctx context.Context, id pgtype.UUID) (ModelTrainingRequest, error)
	GetModelTrainingRequestByUserAndIdempotencyKey(ctx context.Context, arg GetModelTrainingRequestByUserAndIdempotencyKeyParams) (ModelTrainingRequest, error)
	GetOAuthIdentityByProviderSubject(ctx context.Context, arg GetOAuthIdentityByProviderSubjectParams) (AuthOauthIdentity, error)
	GetPendingCarServiceApplicationByUserID(ctx context.Context, userID pgtype.UUID) (CarServiceApplication, error)
	GetPendingRepairRequestByUserAnalysisAndService(ctx context.Context, arg GetPendingRepairRequestByUserAnalysisAndServiceParams) (RepairRequest, error)
	GetRepairRequestByID(ctx context.Context, id pgtype.UUID) (RepairRequest, error)
	GetRepairRequestByIDAndCarServiceProfileID(ctx context.Context, arg GetRepairRequestByIDAndCarServiceProfileIDParams) (RepairRequest, error)
	GetUniversalCarModel(ctx context.Context) (CarModel, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetVehicleGenerationByID(ctx context.Context, id pgtype.UUID) (VehicleGeneration, error)
	GetVehicleGenerationDetailsByID(ctx context.Context, id pgtype.UUID) (GetVehicleGenerationDetailsByIDRow, error)
	GetVehicleMakeByID(ctx context.Context, id pgtype.UUID) (VehicleMake, error)
	GetVehicleModelByID(ctx context.Context, id pgtype.UUID) (VehicleModel, error)
	ListActiveDamageTypes(ctx context.Context) ([]DamageType, error)
	ListActivePartCategories(ctx context.Context) ([]PartCategory, error)
	ListAllDamageTypes(ctx context.Context) ([]DamageType, error)
	ListAnalysisJobsByUserID(ctx context.Context, arg ListAnalysisJobsByUserIDParams) ([]AnalysisJob, error)
	ListCarModels(ctx context.Context, arg ListCarModelsParams) ([]CarModel, error)
	ListCarServiceApplicationsByUserID(ctx context.Context, arg ListCarServiceApplicationsByUserIDParams) ([]CarServiceApplication, error)
	ListCarServiceApplicationsForAdmin(ctx context.Context, arg ListCarServiceApplicationsForAdminParams) ([]CarServiceApplication, error)
	ListCarServiceImagesByProfileID(ctx context.Context, profileID pgtype.UUID) ([]CarServiceImage, error)
	ListCarServiceReviewsByProfileID(ctx context.Context, arg ListCarServiceReviewsByProfileIDParams) ([]CarServiceReview, error)
	ListCarServiceReviewsByUserID(ctx context.Context, arg ListCarServiceReviewsByUserIDParams) ([]CarServiceReview, error)
	ListCarServiceSpecializationsByProfileID(ctx context.Context, profileID pgtype.UUID) ([]CarServiceSpecialization, error)
	ListMatchingCarServices(ctx context.Context, arg ListMatchingCarServicesParams) ([]ListMatchingCarServicesRow, error)
	ListModelTrainingRequestsByUserID(ctx context.Context, arg ListModelTrainingRequestsByUserIDParams) ([]ModelTrainingRequest, error)
	ListModelTrainingRequestsForAdmin(ctx context.Context, arg ListModelTrainingRequestsForAdminParams) ([]ModelTrainingRequest, error)
	ListRepairRequestsByCarServiceProfileID(ctx context.Context, arg ListRepairRequestsByCarServiceProfileIDParams) ([]RepairRequest, error)
	ListRepairRequestsByUserID(ctx context.Context, arg ListRepairRequestsByUserIDParams) ([]RepairRequest, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVehicleGenerationsByModelID(ctx context.Context, modelID pgtype.UUID) ([]VehicleGeneration, error)
	ListVehicleGenerationsByModelIDForAdmin(ctx context.Context, modelID pgtype.UUID) ([]VehicleGeneration, error)
	ListVehicleMakes(ctx context.Context) ([]VehicleMake, error)
	ListVehicleMakesForAdmin(ctx context.Context) ([]VehicleMake, error)
	ListVehicleModelsByMakeID(ctx context.Context, makeID pgtype.UUID) ([]VehicleModel, error)
	ListVehicleModelsByMakeIDForAdmin(ctx context.Context, makeID pgtype.UUID) ([]VehicleModel, error)
	NextCarServiceImageSortOrder(ctx context.Context, profileID pgtype.UUID) (int32, error)
	RejectCarServiceApplication(ctx context.Context, arg RejectCarServiceApplicationParams) (int64, error)
	RespondPendingRepairRequestByCarServiceProfileID(ctx context.Context, arg RespondPendingRepairRequestByCarServiceProfileIDParams) (int64, error)
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error)
	RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error
	SetCarServiceProfileActive(ctx context.Context, arg SetCarServiceProfileActiveParams) (int64, error)
	SetPrimaryCarServiceImage(ctx context.Context, id pgtype.UUID) (int64, error)
	SetVehicleGenerationActive(ctx context.Context, arg SetVehicleGenerationActiveParams) (int64, error)
	SetVehicleMakeActive(ctx context.Context, arg SetVehicleMakeActiveParams) (int64, error)
	SetVehicleModelActive(ctx context.Context, arg SetVehicleModelActiveParams) (int64, error)
	TouchLastUsed(ctx context.Context, arg TouchLastUsedParams) (int64, error)
	UpdateAnalysisJobResult(ctx context.Context, arg UpdateAnalysisJobResultParams) (int64, error)
	UpdateAnalysisJobResultByCorrelationID(ctx context.Context, arg UpdateAnalysisJobResultByCorrelationIDParams) (int64, error)
	UpdateAnalysisJobStatus(ctx context.Context, arg UpdateAnalysisJobStatusParams) (int64, error)
	UpdateAnalysisJobStatusByCorrelationID(ctx context.Context, arg UpdateAnalysisJobStatusByCorrelationIDParams) (int64, error)
	UpdateCarServiceProfile(ctx context.Context, arg UpdateCarServiceProfileParams) (int64, error)
	UpdateCarServiceReviewByRepairRequestIDAndUserID(ctx context.Context, arg UpdateCarServiceReviewByRepairRequestIDAndUserIDParams) (CarServiceReview, error)
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) (int64, error)
	UpdateModelTrainingRequestStatus(ctx context.Context, arg UpdateModelTrainingRequestStatusParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
	UpdateUserContactProfile(ctx context.Context, arg UpdateUserContactProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (int64, error)
	UpdateVehicleGeneration(ctx context.Context, arg UpdateVehicleGenerationParams) (int64, error)
	UpdateVehicleMake(ctx context.Context, arg UpdateVehicleMakeParams) (int64, error)
	UpdateVehicleModel(ctx context.Context, arg UpdateVehicleModelParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
