// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	GetAuthSessionByTokenHash(ctx context.Context, tokenHash string) (AuthSession, error)
	GetOAuthIdentityByProviderSubject(ctx context.Context, arg GetOAuthIdentityByProviderSubjectParams) (AuthOauthIdentity, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error)
	RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error
	TouchLastUsed(ctx context.Context, arg TouchLastUsedParams) (int64, error)
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
