// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (id, user_id, token_hash, token_family_id, replaced_by_id,
                                   user_agent, ip_address,
                                   expires_at, revoked_at, revoked_reason,
                                   created_at, last_used_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7,
        $8, $9, $10,
        $11, $12)
`

type CreateAuthSessionParams struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	TokenHash     string
	TokenFamilyID pgtype.UUID
	ReplacedByID  pgtype.UUID
	UserAgent     *string
	IpAddress     *netip.Addr
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedReason *string
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.TokenFamilyID,
		arg.ReplacedByID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.RevokedReason,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const getAuthSessionByTokenHash = `-- name: GetAuthSessionByTokenHash :one
SELECT id,
       user_id,
       token_hash,
       token_family_id,
       replaced_by_id,
       user_agent,
       ip_address,
       expires_at,
       revoked_at,
       revoked_reason,
       last_used_at,
       created_at,
       updated_at
FROM auth_sessions
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetAuthSessionByTokenHash(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByTokenHash, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenFamilyID,
		&i.ReplacedByID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE auth_sessions
SET revoked_at     = NOW(),
    revoked_reason = $1,
    replaced_by_id = $2
WHERE id = $3
  AND revoked_at IS NULL
`

type RevokeAuthSessionParams struct {
	RevokedReason *string
	ReplacedByID  pgtype.UUID
	ID            pgtype.UUID
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.RevokedReason, arg.ReplacedByID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE auth_sessions
SET revoked_at     = NOW(),
    revoked_reason = $1
WHERE token_family_id = $2
  AND revoked_at IS NULL
`

type RevokeFamilyParams struct {
	RevokedReason *string
	TokenFamilyID pgtype.UUID
}

func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeFamily, arg.RevokedReason, arg.TokenFamilyID)
	return err
}

const touchLastUsed = `-- name: TouchLastUsed :execrows
UPDATE auth_sessions
SET last_used_at = $1
WHERE id = $2
`

type TouchLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) TouchLastUsed(ctx context.Context, arg TouchLastUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchLastUsed, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
