// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, email, avatar_url, password_hash, role,
                   email_verified, is_active,
                   created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8,
        $9, $10)
`

type CreateUserParams struct {
	ID            pgtype.UUID
	Username      string
	Email         string
	AvatarUrl     *string
	PasswordHash  string
	Role          string
	EmailVerified *bool
	IsActive      *bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
		arg.PasswordHash,
		arg.Role,
		arg.EmailVerified,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,
       username,
       email,
       password_hash,
       role,
       email_verified,
       is_active,
       created_at,
       updated_at,
       last_login,
       avatar_url
FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
       username,
       email,
       password_hash,
       role,
       email_verified,
       is_active,
       created_at,
       updated_at,
       last_login,
       avatar_url
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.AvatarUrl,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, role,
       email_verified, is_active,
       created_at, updated_at, last_login, avatar_url
FROM users
ORDER BY created_at DESC
    LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.EmailVerified,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :execrows
UPDATE users SET last_login = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, updateLastLogin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET username       = $1,
    email          = $2,
    avatar_url     = $3,
    password_hash  = $4,
    role           = $5,
    email_verified = $6,
    is_active      = $7
WHERE id = $8
`

type UpdateUserParams struct {
	Username      string
	Email         string
	AvatarUrl     *string
	PasswordHash  string
	Role          string
	EmailVerified *bool
	IsActive      *bool
	ID            pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
		arg.PasswordHash,
		arg.Role,
		arg.EmailVerified,
		arg.IsActive,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserRole = `-- name: UpdateUserRole :execrows
UPDATE users
SET role = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
