// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicleGeneration = `-- name: CreateVehicleGeneration :exec
INSERT INTO vehicle_generations (
    id,
    model_id,
    name,
    slug,
    year_from,
    year_to,
    is_active,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateVehicleGenerationParams struct {
	ID        pgtype.UUID
	ModelID   pgtype.UUID
	Name      string
	Slug      string
	YearFrom  int32
	YearTo    *int32
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateVehicleGeneration(ctx context.Context, arg CreateVehicleGenerationParams) error {
	_, err := q.db.Exec(ctx, createVehicleGeneration,
		arg.ID,
		arg.ModelID,
		arg.Name,
		arg.Slug,
		arg.YearFrom,
		arg.YearTo,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createVehicleMake = `-- name: CreateVehicleMake :exec
INSERT INTO vehicle_makes (
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateVehicleMakeParams struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateVehicleMake(ctx context.Context, arg CreateVehicleMakeParams) error {
	_, err := q.db.Exec(ctx, createVehicleMake,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createVehicleModel = `-- name: CreateVehicleModel :exec
INSERT INTO vehicle_models (
    id,
    make_id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateVehicleModelParams struct {
	ID        pgtype.UUID
	MakeID    pgtype.UUID
	Name      string
	Slug      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateVehicleModel(ctx context.Context, arg CreateVehicleModelParams) error {
	_, err := q.db.Exec(ctx, createVehicleModel,
		arg.ID,
		arg.MakeID,
		arg.Name,
		arg.Slug,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getVehicleGenerationByID = `-- name: GetVehicleGenerationByID :one
SELECT id,
       model_id,
       name,
       slug,
       year_from,
       year_to,
       is_active,
       created_at,
       updated_at
FROM vehicle_generations
WHERE id = $1
`

func (q *Queries) GetVehicleGenerationByID(ctx context.Context, id pgtype.UUID) (VehicleGeneration, error) {
	row := q.db.QueryRow(ctx, getVehicleGenerationByID, id)
	var i VehicleGeneration
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Name,
		&i.Slug,
		&i.YearFrom,
		&i.YearTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleGenerationDetailsByID = `-- name: GetVehicleGenerationDetailsByID :one
SELECT make.id                AS make_id,
       make.name              AS make_name,
       make.slug              AS make_slug,
       make.is_active         AS make_is_active,
       make.created_at        AS make_created_at,
       make.updated_at        AS make_updated_at,
       model.id               AS model_id,
       model.make_id          AS model_make_id,
       model.name             AS model_name,
       model.slug             AS model_slug,
       model.is_active        AS model_is_active,
       model.created_at       AS model_created_at,
       model.updated_at       AS model_updated_at,
       generation.id          AS generation_id,
       generation.model_id    AS generation_model_id,
       generation.name        AS generation_name,
       generation.slug        AS generation_slug,
       generation.year_from   AS generation_year_from,
       generation.year_to     AS generation_year_to,
       generation.is_active   AS generation_is_active,
       generation.created_at  AS generation_created_at,
       generation.updated_at  AS generation_updated_at
FROM vehicle_generations generation
JOIN vehicle_models model ON model.id = generation.model_id
JOIN vehicle_makes make ON make.id = model.make_id
WHERE generation.id = $1
  AND generation.is_active = TRUE
  AND model.is_active = TRUE
  AND make.is_active = TRUE
`

type GetVehicleGenerationDetailsByIDRow struct {
	MakeID              pgtype.UUID
	MakeName            string
	MakeSlug            string
	MakeIsActive        bool
	MakeCreatedAt       pgtype.Timestamptz
	MakeUpdatedAt       pgtype.Timestamptz
	ModelID             pgtype.UUID
	ModelMakeID         pgtype.UUID
	ModelName           string
	ModelSlug           string
	ModelIsActive       bool
	ModelCreatedAt      pgtype.Timestamptz
	ModelUpdatedAt      pgtype.Timestamptz
	GenerationID        pgtype.UUID
	GenerationModelID   pgtype.UUID
	GenerationName      string
	GenerationSlug      string
	GenerationYearFrom  int32
	GenerationYearTo    *int32
	GenerationIsActive  bool
	GenerationCreatedAt pgtype.Timestamptz
	GenerationUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetVehicleGenerationDetailsByID(ctx context.Context, id pgtype.UUID) (GetVehicleGenerationDetailsByIDRow, error) {
	row := q.db.QueryRow(ctx, getVehicleGenerationDetailsByID, id)
	var i GetVehicleGenerationDetailsByIDRow
	err := row.Scan(
		&i.MakeID,
		&i.MakeName,
		&i.MakeSlug,
		&i.MakeIsActive,
		&i.MakeCreatedAt,
		&i.MakeUpdatedAt,
		&i.ModelID,
		&i.ModelMakeID,
		&i.ModelName,
		&i.ModelSlug,
		&i.ModelIsActive,
		&i.ModelCreatedAt,
		&i.ModelUpdatedAt,
		&i.GenerationID,
		&i.GenerationModelID,
		&i.GenerationName,
		&i.GenerationSlug,
		&i.GenerationYearFrom,
		&i.GenerationYearTo,
		&i.GenerationIsActive,
		&i.GenerationCreatedAt,
		&i.GenerationUpdatedAt,
	)
	return i, err
}

const getVehicleMakeByID = `-- name: GetVehicleMakeByID :one
SELECT id,
       name,
       slug,
       is_active,
       created_at,
       updated_at
FROM vehicle_makes
WHERE id = $1
`

func (q *Queries) GetVehicleMakeByID(ctx context.Context, id pgtype.UUID) (VehicleMake, error) {
	row := q.db.QueryRow(ctx, getVehicleMakeByID, id)
	var i VehicleMake
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleModelByID = `-- name: GetVehicleModelByID :one
SELECT id,
       make_id,
       name,
       slug,
       is_active,
       created_at,
       updated_at
FROM vehicle_models
WHERE id = $1
`

func (q *Queries) GetVehicleModelByID(ctx context.Context, id pgtype.UUID) (VehicleModel, error) {
	row := q.db.QueryRow(ctx, getVehicleModelByID, id)
	var i VehicleModel
	err := row.Scan(
		&i.ID,
		&i.MakeID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVehicleGenerationsByModelID = `-- name: ListVehicleGenerationsByModelID :many
SELECT id,
       model_id,
       name,
       slug,
       year_from,
       year_to,
       is_active,
       created_at,
       updated_at
FROM vehicle_generations
WHERE model_id = $1
  AND is_active = TRUE
ORDER BY year_from DESC, name
`

func (q *Queries) ListVehicleGenerationsByModelID(ctx context.Context, modelID pgtype.UUID) ([]VehicleGeneration, error) {
	rows, err := q.db.Query(ctx, listVehicleGenerationsByModelID, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleGeneration
	for rows.Next() {
		var i VehicleGeneration
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.Name,
			&i.Slug,
			&i.YearFrom,
			&i.YearTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleGenerationsByModelIDForAdmin = `-- name: ListVehicleGenerationsByModelIDForAdmin :many
SELECT id,
       model_id,
       name,
       slug,
       year_from,
       year_to,
       is_active,
       created_at,
       updated_at
FROM vehicle_generations
WHERE model_id = $1
ORDER BY year_from DESC, name
`

func (q *Queries) ListVehicleGenerationsByModelIDForAdmin(ctx context.Context, modelID pgtype.UUID) ([]VehicleGeneration, error) {
	rows, err := q.db.Query(ctx, listVehicleGenerationsByModelIDForAdmin, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleGeneration
	for rows.Next() {
		var i VehicleGeneration
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.Name,
			&i.Slug,
			&i.YearFrom,
			&i.YearTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleMakes = `-- name: ListVehicleMakes :many
SELECT id,
       name,
       slug,
       is_active,
       created_at,
       updated_at
FROM vehicle_makes
WHERE is_active = TRUE
ORDER BY name
`

func (q *Queries) ListVehicleMakes(ctx context.Context) ([]VehicleMake, error) {
	rows, err := q.db.Query(ctx, listVehicleMakes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleMake
	for rows.Next() {
		var i VehicleMake
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleMakesForAdmin = `-- name: ListVehicleMakesForAdmin :many
SELECT id,
       name,
       slug,
       is_active,
       created_at,
       updated_at
FROM vehicle_makes
ORDER BY name
`

func (q *Queries) ListVehicleMakesForAdmin(ctx context.Context) ([]VehicleMake, error) {
	rows, err := q.db.Query(ctx, listVehicleMakesForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleMake
	for rows.Next() {
		var i VehicleMake
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleModelsByMakeID = `-- name: ListVehicleModelsByMakeID :many
SELECT id,
       make_id,
       name,
       slug,
       is_active,
       created_at,
       updated_at
FROM vehicle_models
WHERE make_id = $1
  AND is_active = TRUE
ORDER BY name
`

func (q *Queries) ListVehicleModelsByMakeID(ctx context.Context, makeID pgtype.UUID) ([]VehicleModel, error) {
	rows, err := q.db.Query(ctx, listVehicleModelsByMakeID, makeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleModel
	for rows.Next() {
		var i VehicleModel
		if err := rows.Scan(
			&i.ID,
			&i.MakeID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleModelsByMakeIDForAdmin = `-- name: ListVehicleModelsByMakeIDForAdmin :many
SELECT id,
       make_id,
       name,
       slug,
       is_active,
       created_at,
       updated_at
FROM vehicle_models
WHERE make_id = $1
ORDER BY name
`

func (q *Queries) ListVehicleModelsByMakeIDForAdmin(ctx context.Context, makeID pgtype.UUID) ([]VehicleModel, error) {
	rows, err := q.db.Query(ctx, listVehicleModelsByMakeIDForAdmin, makeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleModel
	for rows.Next() {
		var i VehicleModel
		if err := rows.Scan(
			&i.ID,
			&i.MakeID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVehicleGenerationActive = `-- name: SetVehicleGenerationActive :execrows
UPDATE vehicle_generations
SET is_active = $2,
    updated_at = $3
WHERE id = $1
`

type SetVehicleGenerationActiveParams struct {
	ID        pgtype.UUID
	IsActive  bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetVehicleGenerationActive(ctx context.Context, arg SetVehicleGenerationActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVehicleGenerationActive, arg.ID, arg.IsActive, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVehicleMakeActive = `-- name: SetVehicleMakeActive :execrows
UPDATE vehicle_makes
SET is_active = $2,
    updated_at = $3
WHERE id = $1
`

type SetVehicleMakeActiveParams struct {
	ID        pgtype.UUID
	IsActive  bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetVehicleMakeActive(ctx context.Context, arg SetVehicleMakeActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVehicleMakeActive, arg.ID, arg.IsActive, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVehicleModelActive = `-- name: SetVehicleModelActive :execrows
UPDATE vehicle_models
SET is_active = $2,
    updated_at = $3
WHERE id = $1
`

type SetVehicleModelActiveParams struct {
	ID        pgtype.UUID
	IsActive  bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetVehicleModelActive(ctx context.Context, arg SetVehicleModelActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVehicleModelActive, arg.ID, arg.IsActive, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVehicleGeneration = `-- name: UpdateVehicleGeneration :execrows
UPDATE vehicle_generations
SET model_id = $2,
    name = $3,
    slug = $4,
    year_from = $5,
    year_to = $6,
    updated_at = $7
WHERE id = $1
`

type UpdateVehicleGenerationParams struct {
	ID        pgtype.UUID
	ModelID   pgtype.UUID
	Name      string
	Slug      string
	YearFrom  int32
	YearTo    *int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateVehicleGeneration(ctx context.Context, arg UpdateVehicleGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVehicleGeneration,
		arg.ID,
		arg.ModelID,
		arg.Name,
		arg.Slug,
		arg.YearFrom,
		arg.YearTo,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVehicleMake = `-- name: UpdateVehicleMake :execrows
UPDATE vehicle_makes
SET name = $2,
    slug = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateVehicleMakeParams struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateVehicleMake(ctx context.Context, arg UpdateVehicleMakeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVehicleMake,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVehicleModel = `-- name: UpdateVehicleModel :execrows
UPDATE vehicle_models
SET make_id = $2,
    name = $3,
    slug = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateVehicleModelParams struct {
	ID        pgtype.UUID
	MakeID    pgtype.UUID
	Name      string
	Slug      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateVehicleModel(ctx context.Context, arg UpdateVehicleModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVehicleModel,
		arg.ID,
		arg.MakeID,
		arg.Name,
		arg.Slug,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
